    <nav id="mainMenu" class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html"><img src="img/logo.png" alt="logo">旺田科技</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="index.html">首页</a></li>
            <li><a href="aboutus.html">企业介绍</a></li>
            <li><a href="aboutus.html">发展目标</a></li>
            <li><a href="aboutus.html">用户登录</a></li>
            <li><a href="aboutus.html">联系我们</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>